apply plugin: 'com.android.application'

android {
    namespace 'com.extropos.java'
    compileSdk 34
    buildToolsVersion "34.0.0"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.extropos.java"
        minSdkVersion 21
        targetSdkVersion 34
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation ('androidx.appcompat:appcompat:1.6.1') {
        exclude group: 'org.jetbrains.kotlin'
    }
    implementation ('androidx.core:core:1.12.0') {
        exclude group: 'org.jetbrains.kotlin'
    }
    implementation ('androidx.fragment:fragment:1.6.1') {
        exclude group: 'org.jetbrains.kotlin'
    }
    implementation ('androidx.lifecycle:lifecycle-runtime:2.6.1') {
        exclude group: 'org.jetbrains.kotlin'
    }
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    implementation files('libs/AndroidEasingFunctions-1.0.0.jar')
    implementation files('libs/btsdk.jar')
    implementation files('libs/NineOldAndroid-2.4.0.jar')
    implementation 'com.daimajia.androidanimations:library:2.4@aar'
}
