apply plugin: 'com.android.application'

android {
    namespace 'com.extropos.java'
    compileSdk 34
    buildToolsVersion "34.0.0"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.extropos.java"
        minSdkVersion 21
        targetSdkVersion 34
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.fragment:fragment:1.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation files('libs/AndroidEasingFunctions-1.0.0.jar')
    implementation files('libs/btsdk.jar')
    implementation files('libs/NineOldAndroid-2.4.0.jar')
    implementation 'com.daimajia.androidanimations:library:2.4@aar'

    // Exclude conflicting Kotlin libraries
    configurations {
        all {
            exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
            exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
        }
    }
}
