package com.extropos.java.utils;

import com.extropos.java.models.DailyReportData;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

public class EmailExporter {
    
    public static String generateDailyReportEmail(ArrayList<DailyReportData> reportData, Date selectedDate) {
        StringBuilder content = new StringBuilder();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
        
        content.append("QUICK CASH - DAILY REPORT\n");
        content.append("========================\n\n");
        content.append("Date: ").append(dateFormat.format(selectedDate)).append("\n");
        content.append("Generated: ").append(dateFormat.format(new Date())).append("\n\n");
        
        double totalSales = 0;
        int totalOrders = 0;
        double totalTax = 0;
        
        content.append("SUMMARY\n");
        content.append("-------\n");
        
        for (DailyReportData data : reportData) {
            totalSales += data.getTotalAmount();
            totalOrders += data.getOrderCount();
            totalTax += data.getTaxAmount();
        }
        
        String currency = Shared.read(Constants.KEY_SETTING_CURRENCY_SYMBOL, Constants.VAL_DEFAULT_CURRENCY_SYMBOL);
        content.append("Total Sales: ").append(currency).append(String.format("%.2f", totalSales)).append("\n");
        content.append("Total Orders: ").append(totalOrders).append("\n");
        content.append("Total Tax: ").append(currency).append(String.format("%.2f", totalTax)).append("\n\n");
        
        content.append("DETAILED BREAKDOWN\n");
        content.append("------------------\n");
        
        for (DailyReportData data : reportData) {
            content.append("Period: ").append(data.getPeriod()).append("\n");
            content.append("Orders: ").append(data.getOrderCount()).append("\n");
            content.append("Amount: ").append(currency).append(String.format("%.2f", data.getTotalAmount())).append("\n");
            content.append("Tax: ").append(currency).append(String.format("%.2f", data.getTaxAmount())).append("\n");
            if (data.getPaymentMethod() != null) {
                content.append("Payment: ").append(data.getPaymentMethod()).append("\n");
            }
            content.append("----\n");
        }
        
        content.append("\nGenerated by Quick Cash POS System\n");
        content.append("Extro Target SDN BHD\n");
        
        return content.toString();
    }
    
    public static String generateHourlyReportEmail(ArrayList<DailyReportData> reportData, Date selectedDate) {
        // Similar structure for hourly reports
        StringBuilder content = new StringBuilder();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.getDefault());
        
        content.append("QUICK CASH - HOURLY REPORT\n");
        content.append("==========================\n\n");
        content.append("Date: ").append(dateFormat.format(selectedDate)).append("\n\n");
        
        // Add hourly breakdown logic here
        for (DailyReportData data : reportData) {
            content.append("Hour: ").append(data.getPeriod()).append("\n");
            content.append("Sales: ").append(String.format("%.2f", data.getTotalAmount())).append("\n");
            content.append("Orders: ").append(data.getOrderCount()).append("\n");
            content.append("----\n");
        }
        
        content.append("\nGenerated by Quick Cash POS System\n");
        return content.toString();
    }
    
    public static String generateMonthlyReportEmail(ArrayList<DailyReportData> reportData, Date selectedDate) {
        // Similar structure for monthly reports
        StringBuilder content = new StringBuilder();
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/yyyy", Locale.getDefault());
        
        content.append("QUICK CASH - MONTHLY REPORT\n");
        content.append("===========================\n\n");
        content.append("Month: ").append(dateFormat.format(selectedDate)).append("\n\n");
        
        // Add monthly breakdown logic here
        double totalSales = 0;
        int totalOrders = 0;
        
        for (DailyReportData data : reportData) {
            totalSales += data.getTotalAmount();
            totalOrders += data.getOrderCount();
        }
        
        String currency = Shared.read(Constants.KEY_SETTING_CURRENCY_SYMBOL, Constants.VAL_DEFAULT_CURRENCY_SYMBOL);
        content.append("Monthly Sales: ").append(currency).append(String.format("%.2f", totalSales)).append("\n");
        content.append("Monthly Orders: ").append(totalOrders).append("\n\n");
        
        content.append("DAILY BREAKDOWN\n");
        content.append("---------------\n");
        
        for (DailyReportData data : reportData) {
            content.append("Date: ").append(data.getPeriod()).append("\n");
            content.append("Sales: ").append(currency).append(String.format("%.2f", data.getTotalAmount())).append("\n");
            content.append("Orders: ").append(data.getOrderCount()).append("\n");
            content.append("----\n");
        }
        
        content.append("\nGenerated by Quick Cash POS System\n");
        return content.toString();
    }
}